version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.0
    
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: cd my-app && npm install
      - run:
          name: ng install
          command: npm install ng
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build the application
          command: cd my-app && npm run build && ls && pwd
             
#       - run:
#       #Get all pre-requisites
#           command: |
#             yum install python3
#             pip install awscli==1.14.37
#             aws s3 sync ./ s3://production-another-app

      - persist_to_workspace:
          root: ./
          paths:
#             - package.json
#             - node_modules
#             - src
              - my-app/dist
#               - "**/*"
  deploy-test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          #Get all pre-requisites
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.14.37
            aws_login=`aws ecr get-login --no-include-email --region us-east-1`
            eval $aws_login
            aws s3 sync ./my-app/dist/angular-nodejs-example/ s3://test-another-app
  deploy-production:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          #Get all pre-requisites
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.14.37
            aws_login=`aws ecr get-login --no-include-email --region us-east-1`
            eval $aws_login
            aws s3 sync ./my-app/dist/angular-nodejs-example/ s3://production-another-app
  deploy-infrastructure:
    docker:
      - image: hashicorp/terraform
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          #Get all pre-requisites
          command: |
            terraform init
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy-test:
          requires:
            - build
          filters:
            branches:
              only:
                - test
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy-infrastructure:
          requires:
            - build
          filters:
            branches:
              only:
                - master
